apps/adoption/urls.py
from django.conf.urls import url 
from apps.adoption.views import index_adoption

app_name='adoption'
urlpatterns = [
    url(r'^index$', index_adoption)
]

apps/pet/urls.py
from django.conf.urls import url, include
from apps.pet.views import index, pet_view, pet_list, pet_edit, pet_delete


app_name='pet'

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^new$', pet_view, name='pet_create'),
    url(r'^list$', pet_list, name='pet_list'),
    url(r'^edit/(?P<id_pet>\d+)/$', pet_edit, name='pet_edit'),
    url(r'^delete/(?P<id_pet>\d+)/$', pet_delete, name='pet_delete'),



]

petrescue/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^pet/', include (('apps.pet.urls','pet'),namespace='pet')),
    url(r'^adoption/', include (('apps.adoption.urls','adoption'), namespace='adoption')),
]

apps/adoption/models.py
from django.db import models

# Create your models here.
class Person(models.Model):
    name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=70)
    age = models.IntegerField()
    phone = models.CharField(max_length=12)
    email= models.EmailField()
    address = models.TextField()

    def __str__(self):
        return '{} {}'.format(self.name, self.last_name)

apps/pet/models.py
from django.db import models
from apps.adoption.models import Person

# Create your models here.

class Vaccine(models.Model):
    name = models.CharField(max_length=25)
    expiration_date = models.DateField()

    def __str__(self):
        return '{}'.format(self.name)


class Pet(models.Model):
    name = models.CharField(max_length=50)
    sexpet = models.CharField(max_length=10)
    age = models.IntegerField()
    rescue_date = models.DateField()
    person = models.ForeignKey(Person, null=True, blank=True, on_delete=models.CASCADE)
    vaccine = models.ManyToManyField(Vaccine, blank=True)

    def __str__(self):
        return '{}'.format(self.name)

apps/pet/forms.py
from django import forms
from apps.pet.models import Pet


class PetForm(forms.ModelForm):
    class Meta:
        model = Pet

        fields = [
            'name',
            'sexpet',
            'age',
            'rescue_date',
            'person',
            'vaccine',
        ]
        labels ={
            'name': 'Name',
            'sexpet': 'Sex Pet',
            'age': 'Age',
            'rescue_date': 'Rescued',
            'person': 'Owner',
            'vaccine': 'Vaccines',
        }
        widgets = {
            'name': forms.TextInput(attrs={'class':'form-control'}),
            'sexpet': forms.TextInput(attrs={'class':'form-control'}),
            'age': forms.TextInput(attrs={'class':'form-control'}),
            'rescue_date': forms.TextInput(attrs={'class':'form-control'}),
            'person': forms.Select(attrs={'class':'form-control'}),
            'vaccine': forms.CheckboxSelectMultiple(),
        }

apps/adoption/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
app_name = 'adoption'

def index_adoption(request):
    return HttpResponse("This is the main page for adoption")

apps/pet/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

from apps.pet.forms import PetForm
from apps.pet.models import Pet
# Create your views here.
app_name='pet'

def index(request):
    return render(request, 'pet/index.html')

def pet_view(request):
    if request.method == 'POST':
        form = PetForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('pet:index')
    else:
        form = PetForm()
    
    return render(request, 'pet/pet_form.html', {'form':form})

def pet_list(request):
    pet = Pet.objects.all()
    context = {'pets':pet}
    return render(request, 'pet/pet_list.html', context)

def pet_edit(request, id_pet):
    pet = Pet.objects.get(id=id_pet)
    if request.method == 'GET':
        form = PetForm(instance=pet)
    else:
        form = PetForm(request.POST, instance=pet)
        if form.is_valid():
            form.save()
        return redirect('pet:pet_list')
    
    return render(request, 'pet/pet_form.html',{'form':form})

def pet_delete(request, id_pet):
    pet = Pet.objects.get(id=id_pet)
    if request.method == 'POST':
        pet.delete()
        return redirect('pet:pet_list')
    
    return render(request, 'pet/pet_delete.html', {'pet':pet})

templates/base/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"
        <title>{% block title%} Document {% endblock %}</title>

    </head>
    <body>
       
    <div class="container">
        {% block navbar %}
		<div class="bs-docs-section clearfix">
		    <div class="row">
		        <div class="col-lg-12">
		            <div class="bs-component">
		            	<nav class="navbar navbar-default">
		                	<div class="container-fluid">
		                  		<div class="navbar-header">
		                    		<a class="navbar-brand" href="#">Home</a>
		                  		</div>
		                  	<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		                    	<ul class="nav navbar-nav">
		                      		<li class="dropdown">
		                        		<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Mascotas <span class="caret"></span></a>
				                        <ul class="dropdown-menu" role="menu">
				                        	<li><a href="#">Registrar</a></li>
				                        	<li><a href="#">Listar</a></li>
				                        </ul>
		                      		</li>
			                        <li class="dropdown">
			                        	<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Adopciones<span class="caret"></span></a>
			                        	<ul class="dropdown-menu" role="menu">
				                          	<li><a href="#">Solicitar</a></li>
				                          	<li><a href="#">Listar solicitudes</a></li>
			                        	</ul>
			                        </li>
		                    	</ul>
		                    	<ul class="nav navbar-nav navbar-right">
		                        	<li class="dropdown"><a href="http://codigofacilito.com" onclick="pageTracker._link(this.href); return false;">Código Facilito</a>
		                        	</li>
		                        	<li class="dropdown">
		                        		<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Opciones<span class="caret"></span></a>
		                        		<ul class="dropdown-menu" role="menu">
		                          			<li><a href="#">Salir</a></li>
		                        		</ul>
		                      		</li>
		                    	</ul>
		                    </div>
		                </div>
		            </nav>
		        </div>
           	</div>
        </div>
    </div>    

	{% endblock %}

        {% block content %}
        <h5>This is the content for the base template</h5>
        {% endblock %}
  
        
        {% block footer %}
        <h5>This is the footer for the base template</h5>
        {% endblock %}
  </div>

        <script src="https://code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="
  crossorigin="anonymous"></script>

	<script src="{% static 'js/bootstrap.min.js' %}"></script>

        {% block extrajs %}
        {% endblock %}

    </body>

</html>

templates/base/header.html
<header>Hello</header>

templates/pet/index.html
{% extends 'base/base.html' %}

{% block title %}
App pet
{% endblock %}



{% block content %}
<h6>i am the content for pet's app</h6>
{% endblock %}

templates/pet/pet_delete.html
{% extends 'base/base.html' %}

{% block content %}
<form method="POST">
    {% csrf_token %}
    <h3>Do you want to delete the record for: {{pet.name}}</h3>
    <button class="btn btn-danger" type="submit">Yes, delete!</button>
    <a class="btn btn-default" href="{% url 'pet:pet_list' %}">Cancel</a>

</form>
{% endblock %}

templates/pet/pet_form.html
{% extends 'base/base.html' %}

{% block content %}
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>

</form>
{% endblock %}

templates/pet/pet_list.html
{% extends 'base/base.html' %}
{% block content %}
<table class="table table-bordered">
<thead>
    <tr>
        <td>#</td>
        <td>Name</td>
        <td>Sex</td>
        <td>Age</td>
        <td>Date Rescued</td>
        <td>Owner pretend</td>
        <td>Action</td>
    </tr>
</thead>
<tbody>
    {% if pets  %}
    {% for pet in pets  %}

    <tr>
        <td>{{ pet.id  }}</td>
        <td>{{ pet.name }}</td>
        <td>{{ pet.sexpet }}</td>
        <td>{{ pet.age }}</td>
        <td>{{ pet.rescue_date }}</td>
        <td>{{ pet.person.name }} {{ pet.person.last_name }}</td>
        <td>
            <a class="btn btn-primary" href="{% url 'pet:pet_edit' pet.id  %}">Edit</a> 
            <a class="btn btn-danger" href="{% url 'pet:pet_delete' pet.id  %}">Delete</a>
        </td>
        

        
    </tr>
    {% endfor %}
    {% else %}
       <h1>There is no records about pets</h1>
     {% endif %}
</tbody>
</table>
{% endblock %}